name: test building multiple executables with CMake

on: [pull_request]

jobs:
  multiple-executables-example:
    runs-on: ubuntu-latest
    container: ghcr.io/armmbed/mbed-os-env:master-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive   # fetch submodules

      - name: Verify submodules present
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git submodule status
          test -f cmsis/CMSIS-RTX/Config/RTX_Config.h
          test -f cmsis/CMSIS_6/CMSIS/Core/Include/cmsis_version.h

      - name: Install Python packages
        # Note: pip>=20.3 is needed to install dependencies of cysecuretools
        run: |
          python3 -m pip install --upgrade pip
          
          # Remove mbed-tools package that comes with the docker image, it conflicts with the one we want to install
          python3 -m pip uninstall -y mbed-tools
          
          python3 -m pip install -e ./tools
          
          # Also install cysecuretools which is not installed automatically
          python3 -m pip install 'cysecuretools~=6.0'

      # Note: For this CI job we use MBED_CREATE_PYTHON_VENV=FALSE so that we can make sure
      # this mode works.
      - name: Build the multiple_executables example
        run: |
            cd tools/cmake/tests/multiple_executables/
            mkdir cmake_build
            cd cmake_build
            cmake -DMBED_TARGET=ARM_MUSCA_S1 -DMBED_CREATE_PYTHON_VENV=FALSE ..
            cmake --build .

      - name: Verify the post-build command has run successfully on each image
        run: |
            APP1=tools/cmake/tests/multiple_executables/cmake_build/app1/app1.bin
            APP2=tools/cmake/tests/multiple_executables/cmake_build/app2/app2.bin
            BOOTLOADER=targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/bl2.bin
            BOOTLOADER_SIZE=`du -b targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/bl2.bin | cut -f1`
            cmp -n $BOOTLOADER_SIZE $APP1 $BOOTLOADER
            cmp -n $BOOTLOADER_SIZE $APP2 $BOOTLOADER
